// Generated by dia2code
#ifndef ENGINE__ACTIONLIST__H
#define ENGINE__ACTIONLIST__H

#include <vector>

namespace state {
  class State;
};
namespace engine {
  class Action;
}

#include "Action.h"

namespace engine {

  /// class ActionList - 
  class ActionList {
    // Associations
    // Attributes
  protected:
    state::State& s;
    std::vector<Action*> actions;
    bool notify;
    // Operations
  public:
    ActionList (state::State& s, bool notify);
    ~ActionList ();
    int size () const;
    Action* get (int i) const;
    void apply ();
    void undo ();
    void add (Action* action);
    void addapply (Action* action);
    void clear ();
  };

};

#endif
