// Generated by dia2code
#ifndef ENGINE__ACTION__H
#define ENGINE__ACTION__H


namespace state {
  class State;
}

#include "state/State.h"

namespace engine {

  /// class Action - 
  class Action : public state::State {
    // Operations
  public:
    virtual ~Action ();
    virtual void apply (state::State& s, bool notify) = 0;
    virtual void undo (state::State& s, bool notify) = 0;
  };

};

#endif
