// Generated by dia2code
#ifndef ENGINE__DIRECTIONCOMMAND__H
#define ENGINE__DIRECTIONCOMMAND__H


namespace engine {
  class Command;
}

#include "state/Direction.h"
#include "CommandTypeId.h"
#include "Command.h"

namespace engine {

  /// class DirectionCommand - 
  class DirectionCommand : public engine::Command {
    // Attributes
  protected:
    int character;
    state::Direction direction;
    // Operations
  public:
    DirectionCommand ();
    CommandTypeId getTypeId () const;
    int getCharacter () const;
    state::Direction getDirection () const;
    void setCharacter (int character);
    void setDirection (state::Direction direction);
    void move (int level[15][15]);
  };

};

#endif
