// Generated by dia2code
#ifndef ENGINE__DIRECTIONCOMMAND__H
#define ENGINE__DIRECTIONCOMMAND__H
#include "../state/State.h"
#include <iostream>


namespace engine {
  class Command;
}

#include "CommandTypeId.h"
#include "Command.h"
#include "../state/JoueurTank.h"
#include <SFML/Graphics.hpp>
namespace engine {

  /// class DirectionCommand - 
  class DirectionCommand : public engine::Command {
    // Attributes
  protected:
    int character;
    state::Direction direction;
//    state::JoueurTank jou1 = new state::JoueurTank();
    
    // Operations
  public:
      
    DirectionCommand ();
    CommandTypeId getTypeId () const;
    int getCharacter () const;
    state::Direction getDirection () const;
    void setCharacter (int character);
    void setDirection (state::Direction direction);
    void DirectionJoueur (sf::Sprite jou);
  };

};

#endif
