// Generated by dia2code
#ifndef ENGINE__DIRECTIONCOMMANDBULLET__H
#define ENGINE__DIRECTIONCOMMANDBULLET__H


namespace state {
  class State;
};
namespace engine {
  class Command;
}

#include "state/Direction.h"
#include "Command.h"

namespace engine {

  /// class DirectionCommandBullet - 
  class DirectionCommandBullet : public engine::Command {
    // Attributes
  protected:
    state::Direction direction;
    // Operations
  public:
    DirectionCommandBullet (state::Direction id);
    void run (state::State& state);
  };

};

#endif
