// Generated by dia2code
#ifndef ENGINE__DIRECTIONCOMMANDENEMY__H
#define ENGINE__DIRECTIONCOMMANDENEMY__H


namespace state {
  class State;
};
namespace engine {
  class Command;
}

#include "state/Direction.h"
#include "CommandTypeId.h"
#include "Command.h"

namespace engine {

  /// class DirectionCommandEnemy - 
  class DirectionCommandEnemy : public engine::Command {
    // Attributes
  protected:
    int character;
    state::Direction direction;
    int num;
    // Operations
  public:
    DirectionCommandEnemy (int i, state::Direction id);
    CommandTypeId getTypeId () const;
    int getCharacter () const;
    state::Direction getDirection () const;
    void setCharacter (int character);
    void setDirection (state::Direction direction);
    void run (state::State& state);
  };

};

#endif
