// Generated by dia2code
#ifndef ENGINE__ENGINEMODE__H
#define ENGINE__ENGINEMODE__H


namespace engine {

  enum EngineMode {
    PLAY     = 1,
    RECORD     = 2,
    REPLAY     = 3,
    ROLLBACK     = 4,
    PAUSE     = 5,
    CLOSE     = 6
  };

};

#endif
