// Generated by dia2code
#ifndef ENGINE__INCEPOCH__H
#define ENGINE__INCEPOCH__H

#include "../state/State.h"
namespace engine {
  class Action;
}

#include "Action.h"

namespace engine {

  /// class IncEpoch - 
  class IncEpoch : public engine::Action {
    // Operations
  public:
    IncEpoch ();
    void apply (state::State& s, bool notify);
    void undo (state::State& s, bool notify);
  };

};

#endif
