// Generated by dia2code
#ifndef ENGINE__MODECOMMAND__H
#define ENGINE__MODECOMMAND__H


namespace engine {
  class Command;
}

#include "EngineMode.h"
#include "CommandTypeId.h"
#include "Command.h"

namespace engine {

  /// class ModeCommand - 
  class ModeCommand : public engine::Command {
    // Attributes
  public:
    EngineMode mode;
    // Operations
  public:
    ModeCommand (EngineMode mode);
    CommandTypeId getTypeId () const;
    EngineMode getMode () const;
    void setMode (EngineMode mode);
  };

};

#endif
