// Generated by dia2code
#ifndef ENGINE__RECORD__H
#define ENGINE__RECORD__H

#include <vector>

namespace state {
  class State;
};
namespace engine {
  class ActionList;
}

namespace engine {

  /// class Record - 
  class Record {
    // Attributes
  protected:
    state::State& mainState;
    state::State* initState;
    state::State* lastState;
    std::vector<ActionList*> actions;
    int idx;
    // Operations
  public:
    Record (state::State& s);
    ~Record ();
    void clear ();
    void startRecord ();
    /// 										
    /// @param actions		(???) 
    void recordOne (ActionList* actions);
    void stopRecord ();
    void startReplay ();
    bool replayOne ();
    void startRollback ();
    bool rollbackOne ();
  };

};

#endif
