// Generated by dia2code
#ifndef ENGINE__RULER__H
#define ENGINE__RULER__H


namespace state {
  class State;
};
namespace engine {
  class CommandSet;
  class ActionList;
}

#include "ActionList.h"

namespace engine {

  /// class Ruler - 
  class Ruler {
    // Associations
    // Attributes
  protected:
    const state::State& currentState;
    const CommandSet& commands;
    ActionList& actions;
    // Operations
  public:
    Ruler (ActionList& a, const state::State& s, const CommandSet& cs);
    ~Ruler ();
    void collisions ();
    void apply ();
  protected:
    void moveChar (int idx);
    void resChar (int idx);
  };

};

#endif
