// Generated by dia2code
#ifndef RENDER__ANIMATION__H
#define RENDER__ANIMATION__H

#include <stdint.h>

namespace render {
  class Tile;
  class Surface;
}

#include "Tile.h"
#include "../state/Direction.h"
namespace render {

  /// class Animation - 
  class Animation {
    // Associations
    // Attributes
  private:
    int i;
  protected:
    /// 	
    int x;
    int y;
    const Tile* tile;
    state::Direction direction;
    float speed;
    int64_t start;
    // Operations
  public:
    Animation (int i, int x, int y, const Tile* a);
    void setDirection (state::Direction d);
    void setSpeed (float speed);
    void update (int64_t time, Surface* surface);
  };

};

#endif
