// Generated by dia2code
#ifndef RENDER__ANIMATEDTILE__H
#define RENDER__ANIMATEDTILE__H

#include <vector>
#include <stdint.h>

namespace render {
  class Tile;
}

#include "Tile.h"

namespace render {

  /// class AnimatedTile - 
  class AnimatedTile : public render::Tile {
    // Attributes
  protected:
    std::vector<const Tile*> tiles;
    float rate;
    // Operations
  public:
    AnimatedTile (float rate = 10);
    ~AnimatedTile ();
    bool isAnimated () const;
    float getRate () const;
    int getTileCount () const;
    const Tile* getTile (int i) const;
    const Tile* getTile (int64_t time) const;
    void setRate (float rate);
    void addTile (Tile* tile);
    void setTile (int i, Tile* tile);
  };

};

#endif
