// Generated by dia2code
#ifndef RENDER__ELEMENTLISTLAYER__H
#define RENDER__ELEMENTLISTLAYER__H


namespace render {
  class Layer;
}

#include "Layer.h"
#include "../state/ElementList.h"
namespace render {

  /// class ElementListLayer - 
  class ElementListLayer : public render::Layer {
    // Operations
  public:
    void update (const state::ElementList& list, int i);
    void stateChanged (const state::StateEvent& e);
  };

};

#endif
