// Generated by dia2code
#ifndef RENDER__LAYER__H
#define RENDER__LAYER__H

#include <map>

namespace render {
  class Surface;
  class TileSet;
  class Animation;
};
namespace state {
  class StateObserver;
}

#include "state/StateObserver.h"
#include "TileSet.h"
#include "Surface.h"
#include "Animation.h"

namespace render {

  /// class Layer - 
  class Layer : public state::StateObserver {
    // Associations
    // Attributes
  private:
    std::map<int,Animation*> animations;
  protected:
    Surface* surface;
    const TileSet* tileset;
    // Operations
  public:
    Layer ();
    ~Layer ();
    const TileSet* getTileSet () const;
    void setTileSet (const TileSet* tileset);
    void setSurface (Surface* surface);
    void setAnimation (int i, Animation* a);
    void stateChanged (const state::StateEvent& e);
  };

};

#endif
