// Generated by dia2code
#ifndef RENDER__SCENE__H
#define RENDER__SCENE__H

#include <vector>

namespace render {
  class Layer;
};
namespace state {
  class StateObserver;
};
namespace render {
  class ElementListLayer;
}

#include "state/StateObserver.h"
#include "SceneLayer.h"
#include "ElementListLayer.h"

namespace render {

  /// class Scene - 
  class Scene : public state::StateObserver {
    // Associations
    // Attributes
  protected:
    int width;
    int height;
    std::vector<Layer*> layers;
    // Operations
  public:
    Scene ();
    ~Scene ();
    int getWidth () const;
    int getHeight () const;
    int getLayerCount () const;
    Layer* getLayer (int ind) const;
    void setLayer (int ind, Layer* layer);
    void registerObservers (const state::State* s);
    void stateChanged (const state::StateEvent& e);
    void unregisterObservers (const state::State* s);
  };

};

#endif
