// Generated by dia2code
#ifndef RENDER__SCENELAYER__H
#define RENDER__SCENELAYER__H


namespace render {

  enum SceneLayer {
    GRID_LAYER     = 0,
    CHARS_LAYER     = 1,
    BUILDS_LAYER     = 2
  };

};

#endif
