// Generated by dia2code
#ifndef RENDER__SFMLSURFACE__H
#define RENDER__SFMLSURFACE__H

#include <SFML/Graphics.hpp>
#include <string>

namespace render {
  class StaticTile;
};
namespace sf {
  class Transformable;
  class Drawable;
};
namespace render {
  class Surface;
}

#include "sf/Transformable.h"
#include "sf/Drawable.h"
#include "Surface.h"

namespace render {

  /// class SFMLSurface - 
  class SFMLSurface : public sf::Transformable, public sf::Drawable, public render::Surface {
    // Attributes
  protected:
    sf::VertexArray vertices;
    sf::Texture tileset;
    sf::Vertex* quad;
    // Operations
  public:
    void clear ();
    void loadTexture (const char* image_file);
    void setSpriteCount (int n);
    void setSpriteLocation (int i, int x, int y);
    void setSpriteTexture (int i, const StaticTile* tex);
    void draw (sf::RenderTarget& target, sf::RenderStates states) const;
    bool load (const std::string& tileset, sf::Vector2u tileSize, const int* tiles, unsigned int width, unsigned int height);
  };

};

#endif
