// Generated by dia2code
#ifndef RENDER__SURFACE__H
#define RENDER__SURFACE__H
#include <SFML/Graphics.hpp>
#include "render/SFMLSurface.h"
#include "state/JoueurTank.h"
#include "../engine/DirectionCommand.h"
#include "../state/MobileTypeId.h"
    
namespace render {
  class StaticTile;
}

namespace render {

  /// class Surface - 
  class Surface {
    // Operations
  public:
      Surface();
    virtual ~Surface ();
/*    virtual void clear () = 0;
    virtual void loadTexture (const char* image_file) = 0;
    virtual void setSpriteCount (int n) = 0;
    virtual void setSpriteLocation (int i, int x, int y) = 0;
    virtual void setSpriteTexture (int i, const StaticTile* tex) = 0;*/
  };

};

#endif
