// Generated by dia2code
#ifndef RENDER__TILESETCHARS__H
#define RENDER__TILESETCHARS__H

#include <vector>

namespace render {
  class StaticTile;
  class TileSet;
}

#include "TileSet.h"
#include "StaticTile.h"

namespace render {

  /// class TileSetChars - 
  class TileSetChars : public render::TileSet {
    // Associations
    // Attributes
  protected:
    const char* file_name;
    std::vector<StaticTile*> tiles;
    int cellWidth;
    int cellHeight;
    // Operations
  public:
    TileSetChars ();
    int getCellWidth () const;
    int getCellHeight () const;
    const char* getImageFile () const;
  };

};

#endif
