// Generated by dia2code
#ifndef AI__AI__H
#define AI__AI__H


namespace state {
  class State;
};
namespace engine {
  class CommandSet;
}

#include "state/State.h"

namespace ai {

  /// class AI - 
  class AI {
    // Attributes
  protected:
    const state::State& mainState;
    // Operations
  public:
    AI (const state::State& mainState);
    virtual ~AI ();
    virtual void run (engine::CommandSet& commands) = 0;
  protected:
    bool nextLocation (int idx, int x, int y) const;
  };

};

#endif
