// Generated by dia2code
#ifndef STATE__BULLET__H
#define STATE__BULLET__H

#include <vector>

namespace state {
  class JoueurTank;
  class EnemyTank;
  class Element;
  class MobileElement;
}

#include "JoueurTank.h"
#include "EnemyTank.h"
#include "Direction.h"
#include "MobileTypeId.h"
#include "MobileElement.h"

namespace state {

  /// class Bullet - 
  class Bullet : public state::MobileElement {
    // Attributes
  protected:
    JoueurTank joueur;
    EnemyTank et;
    // Operations
  public:
    Bullet ();
    void init (std::vector<int>& level, Direction d);
    Element* clone () const;
    void moveleft (std::vector<int>& level);
    void moveright (std::vector<int>& level);
    void moveup (std::vector<int>& level);
    void movedown (std::vector<int>& level);
    void gene (MobileTypeId type, Direction d);
  };

};

#endif
