// Generated by dia2code
#ifndef STATE__ELEMENTALLOC__H
#define STATE__ELEMENTALLOC__H


namespace state {
  class Element;
  class AElementAlloc;
}

#include "AElementAlloc.h"

namespace state {

  /// class ElementAlloc - 
  template <  class E,   typename ID>
  class ElementAlloc : public state::AElementAlloc {
    // Attributes
  protected:
    ID id;
    // Operations
  public:
    ElementAlloc (ID id);
    Element* newInstance ();
  };

};

#endif
