// Generated by dia2code
#ifndef STATE__ELEMENT__H
#define STATE__ELEMENT__H


namespace state {
  class Element;
}

#include "Direction.h"

namespace state {

  /// class Element - 
  class Element {
    // Attributes
  protected:
    int x;
    int y;
    Direction orientation;
    int life;
    // Operations
  public:
    Element ();
    virtual ~Element ();
    virtual bool isStatic () const = 0;
    virtual Element* clone () const = 0;
    bool equals (const Element& other) const;
    int getX () const;
    int getY () const;
    Direction getOrientation () const;
    int getLife () const;
    void setX (int x);
    void setY (int y);
    void setOrientation (Direction o);
    void setLife (int lifenum);
  };

};

#endif
