// Generated by dia2code
#ifndef STATE__ELEMENTFACTORY__H
#define STATE__ELEMENTFACTORY__H

#include <map>

namespace state {
  class AElementAlloc;
}

#include "AElementAlloc.h"

namespace state {

  /// class ElementFactory - 
  class ElementFactory {
    // Associations
    // Attributes
  protected:
    std::map<char,AElementAlloc*> list;
    // Operations
  public:
    ~ElementFactory ();
    Element* const newInstance (int id);
    void registerType (int id, AElementAlloc* a);
  };

};

#endif
