// Generated by dia2code
#ifndef STATE__ELEMENTLIST__H
#define STATE__ELEMENTLIST__H

#include <vector>

namespace state {
  class State;
  class ElementFactory;
  class Element;
  class ElementList;
  class Observable;
}

#include "Observable.h"
#include "Element.h"
#include "ElementFactory.h"

namespace state {

  /// class ElementList - 
  class ElementList : public state::Observable {
    // Associations
    // Attributes
  protected:
    State& s;
    ElementFactory* factory;
    std::vector<Element*> elements;
    // Operations
  public:
    ElementList (State& s);
    ~ElementList ();
    ElementList* const clone ();
    void copy (const ElementList& list);
    /// 		
    /// @param other		(???) 
    bool const equals (const ElementList& other);
    const State& getState ();
    int const size ();
    Element* const get (int i);
    void clear ();
    void setElementFactory (ElementFactory* f);
    void set (int i, Element* e);
    void const notifyObservers (int i = -1);
    void load (const char* file_name);
  };

};

#endif
