// Generated by dia2code
#ifndef STATE__ENEMYTANK__H
#define STATE__ENEMYTANK__H


namespace state {
  class MobileElement;
}

#include "TankTypeId.h"
#include "MobileElement.h"

namespace state {

  /// class EnemyTank - 
  class EnemyTank : public state::MobileElement {
    // Associations
    state::TankTypeId tankTypeId;
    // Operations
  public:
    EnemyTank ();
    bool const isEnemyTank ();
    TypeId const getTypeId ();
    Element* const clone ();
    void setColor (int c);
    void setTypeId (TankTypeId id);
  };

};

#endif
