// Generated by dia2code
#ifndef STATE__ENEMYTANK__H
#define STATE__ENEMYTANK__H


namespace state {
  class Element;
  class MobileElement;
}

#include "MobileElement.h"

namespace state {

  /// class EnemyTank - 
  class EnemyTank : public state::MobileElement {
    // Operations
  public:
    EnemyTank ();
    bool isEnemyTank () const;
    Element* clone () const;
    void setColor (int c);
  };

};

#endif
