// Generated by dia2code
#ifndef STATE__ENEMYTANK__H
#define STATE__ENEMYTANK__H


namespace state {
  class Element;
  class MobileElement;
}

#include "TypeId.h"
#include "TankTypeId.h"
#include "MobileElement.h"

namespace state {

  /// class EnemyTank - 
  class EnemyTank : public state::MobileElement {
    // Associations
    state::TankTypeId tankTypeId;
    // Operations
  public:
    EnemyTank ();
    bool isEnemyTank () const;
    TypeId getTypeId () const;
    Element* clone () const;
    void setColor (int c);
    void setTypeId (TankTypeId id);
  };

};

#endif
