// Generated by dia2code
#ifndef STATE__HOUSE__H
#define STATE__HOUSE__H


namespace state {
  class StaticElement;
}

#include "StaticElement.h"

namespace state {

  /// class House - 
  class House : public state::StaticElement {
    // Operations
  public:
    House ();
    Element* const clone ();
    void beingattacked ();
  };

};

#endif
