// Generated by dia2code
#ifndef STATE__IRON__H
#define STATE__IRON__H


namespace state {
  class Element;
  class StaticElement;
}

#include "StaticElement.h"

namespace state {

  /// class Iron - 
  class Iron : public state::StaticElement {
    // Operations
  public:
    Iron ();
    Element* clone () const;
    void beingattacked ();
  };

};

#endif
