// Generated by dia2code
#ifndef STATE__JOUEURTANK__H
#define STATE__JOUEURTANK__H


namespace state {
  class MobileElement;
}

#include "MobileElement.h"

namespace state {

  /// class JoueurTank - 
  class JoueurTank : public state::MobileElement {
    // Operations
  public:
    JoueurTank ();
    bool isJoueurTank ();
    Element* const clone ();
    void addlife (int lifenum);
  };

};

#endif
