// Generated by dia2code
#ifndef STATE__JOUEURTANK__H
#define STATE__JOUEURTANK__H


namespace state {
  class Element;
  class MobileElement;
}

#include "MobileTypeId.h"
#include "MobileElement.h"

namespace state {

  /// class JoueurTank - 
  class JoueurTank : public state::MobileElement {
    // Operations
  public:
    JoueurTank (MobileTypeId mi);
    bool isJoueurTank ();
    Element* clone () const;
    void addlife (int lifenum);
  };

};

#endif
