// Generated by dia2code
#ifndef STATE__MOBILETYPEID__H
#define STATE__MOBILETYPEID__H


namespace state {

  enum MobileTypeId {
    JOUEUR     = 0,
    NORMAL     = 1,
    QUICK     = 2,
    HARD     = 3
  };

};

#endif
