// Generated by dia2code
#ifndef STATE__MOBILEELEMENT__H
#define STATE__MOBILEELEMENT__H


namespace state {
  class Element;
}

#include "Direction.h"
#include "Element.h"
#include "MobileStatus.h"

namespace state {

  /// class MobileElement - 
  class MobileElement : public state::Element {
    // Associations
    state::MobileStatus status;
    state::Direction direction;
    // Attributes
  protected:
    int speed;
    int position;
    int color;
    // Operations
  public:
    MobileElement ();
    bool equals (const Element& other) const;
    bool isStatic () const;
    Direction getDirection () const;
    int getSpeed () const;
    int getPosition () const;
    int getColor () const;
    void setDirection (Direction d);
    void setSpeed (int s);
    void setPosition (int position);
    void attack ();
    void beingattacked ();
  };

};

#endif
