// Generated by dia2code
#ifndef STATE__OBSERVABLE__H
#define STATE__OBSERVABLE__H

#include <vector>

namespace state {
  class StateObserver;
  class StateEvent;
}

#include "StateObserver.h"

namespace state {

  /// class Observable - 
  class Observable {
    // Associations
    // Attributes
  protected:
    mutable std::vector<StateObserver*> observers;
    // Operations
  public:
    ~Observable ();
    void registerObserver (StateObserver* o) const;
    void unregisterObserver (StateObserver* o) const;
    void notifyObservers (const StateEvent& e) const;
  };

};

#endif
