// Generated by dia2code
#ifndef STATE__OBSERVABLE__H
#define STATE__OBSERVABLE__H

#include <vector>

namespace state {
  class StateObserver;
  class StateEvent;
}

#include "StateObserver.h"

namespace state {

  /// class Observable - 
  class Observable {
    // Associations
    // Attributes
  protected:
    mutable std::vector<StateObserver*> observers;
    // Operations
  public:
    ~Observable ();
    void const registerObserver (StateObserver* o);
    void const unregisterObserver (StateObserver* o);
    void const notifyObservers (const StateEvent& e);
  };

};

#endif
