// Generated by dia2code
#ifndef STATE__OBSTACLETYPEID__H
#define STATE__OBSTACLETYPEID__H


namespace state {

  enum ObstacleTypeId {
    HOUSE     = 0,
    WOOD     = 1,
    IRON     = 2,
    SEA     = 3
  };

};

#endif
