// Generated by dia2code
#ifndef STATE__SEA__H
#define STATE__SEA__H


namespace state {
  class Element;
  class StaticElement;
}

#include "StaticElement.h"

namespace state {

  /// class Sea - 
  class Sea : public state::StaticElement {
    // Operations
  public:
    
    Sea ();
    Element* clone () const;
  };

};

#endif
