// Generated by dia2code
#ifndef STATE__STATEOBSERVER__H
#define STATE__STATEOBSERVER__H

#include "StateEvent.h"
namespace state {

  /// class StateObserver - 
  class StateObserver {
    // Operations
  public:
    void stateChanged (const StateEvent& e);
  };

};

#endif
