// Generated by dia2code
#ifndef STATE__STATICELEMENTTYPEID__H
#define STATE__STATICELEMENTTYPEID__H


namespace state {

  enum StaticElementTypeId {
    HOUSE     = 0,
    WOOD     = 1,
    IRON     = 2,
    SEA     = 3
  };

};

#endif
