// Generated by dia2code
#ifndef STATE__STATEEVENTID__H
#define STATE__STATEEVENTID__H


namespace state {

  enum StateEventId {
    ALL_CHANGED     = 0,
    LEVEL_CHANGED     = 1,
    EPOCH_CHANGED     = 2,
    LIST_CHANGED     = 3
  };

};

#endif
