// Generated by dia2code
#ifndef STATE__WOOD__H
#define STATE__WOOD__H

#include <vector>

namespace state {
  class Element;
  class StaticElement;
}

#include "StaticElement.h"

namespace state {

  /// class Wood - 
  class Wood : public state::StaticElement {
    // Operations
  public:
    Wood (int x, int y);
    Element* clone () const;
    void beingattacked ();
    void init (std::vector<int>& level);
  };

};

#endif
