// Generated by dia2code
#ifndef STATE__WOOD__H
#define STATE__WOOD__H


namespace state {
  class StaticElement;
}

#include "StaticElement.h"

namespace state {

  /// class Wood - 
  class Wood : public state::StaticElement {
    // Operations
  public:
    Wood ();
    Element* const clone ();
    void beingattacked ();
  };

};

#endif
